# Dockerfile for the backend apis using Node.js and Express

# Use official Node.js image as base image
FROM node:24.4-alpine

# Set working directory for backend
WORKDIR /app

# Copy backend package files
COPY package*.json ./

# Install backend dependencies
RUN npm install

# Copy backend source code
COPY . .

# Expose backend port
EXPOSE 3000

# Start the backend server
CMD ["npx", "nodemon", "app.js"]